=== TrevorDBrown/LinkFree/src/templates/linkfree.json/linkfree.schema.json
{
    "$schema": "http://json-schema.org/draft/2020-12/schema",
    "$id": "https://trevordylanbrown.com/LinkFreePlus/linkfree.schema.json",
    "title": "LinkFreePlus",
    "description": "The configuration file for a LinkFreePlus instance.",
    "type": "object",
    "properties": {
        "displayName": {
            "description": "The display name at the top of a LinkFreePlus instance.",
            "type": "string"
        },
        "tagline": {
            "description": "A brief description or tagline associated with the subject of the LinkFreePlus instance.",
            "type": "string"
        },
        "profilePicture": {
            "description": "The path to an image representing the subject of the LinkFreePlus instance.",
            "type": "string"
        },
        "theme": {
            "description": "The name of the LinkFree/LinkFreePlus theme to be used by the LinkFreePlus instance.",
            "type": "string"
        },
        "linkTrayOnTop": {
            "description": "A boolean representing whether or not the link tray should be placed at the top of bottom of the LinkFreePlus instance.",
            "type": "boolean"
        },
        "linkGroupsAboveUnsorted": {
            "description": "A boolean representing whether or not organized links (i.e. links in a group) should go above or below unsorted links in the LinkFreePlus instance.",
            "type": "boolean"
        },
        "linkGroups": {
            "description": "A collection of link groups to be used for organization within the LinkFreePlus instance. Special groups that do not need to be defined are 'Link Tray' and 'Unsorted'.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "linkGroupName": {
                        "description": "The name of the link group.",
                        "type": "string"
                    },
                    "showLinkGroupName": {
                        "description": "A boolean representing whether or not the link group's name should be visible.",
                        "type": "boolean"
                    },
                    "useLinkIcons": {
                        "description": "A boolean representing whether or not the link should display as text or an icon.",
                        "type": "boolean"
                    },
                    "linkGroupPosition": {
                        "description": "The order in which the group should appear compared to other groups.",
                        "type": "integer",
                        "minimum": 0
                    },
                    "linkGroupEnabled": {
                        "description": "A boolean representing whether or not a group should be visible within the LinkFreePlus instance.",
                        "type": "boolean"
                    }
                }
            }
        },
        "links": {
            "description": "A collection of links displayed within the LinkFreePlus instance.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "linkName": {
                        "description": "The display name of the link (when not in the link tray).",
                        "type": "string"
                    },
                    "linkType": {
                        "description": "The display icon of the link (when in the link tray).",
                        "type": "string"
                    },
                    "linkHref": {
                        "description": "The actual link address.",
                        "type": "string"
                    },
                    "newWindow": {
                        "description": "A boolean representing whether or not a link should open in a new tab/window.",
                        "type": "boolean"
                    },
                    "enabled": {
                        "description": "A boolean representing whether or not a link should be enabled globally (group settings override this value).",
                        "type": "boolean"
                    },
                    "linkGroups": {
                        "description": "A collection of instances of the link within the LinkFreePlus instance. Empty array represents one unsorted instance, if enabled is true.",
                        "type": "array",
                        "items": {
                            "type": "object",
                            "properties": {
                                "linkGroupName": {
                                    "description": "The name of the link group in which the link should be added. Link group name must be in linkGroups array. Otherwise, it will be ignored and stored as an unsorted link.",
                                    "type": "string"
                                },
                                "linkPosition": {
                                    "description": "The order in which the link should appear relative to other links.",
                                    "type": "integer",
                                    "minimum": 0
                                },
                                "show": {
                                    "description": "A boolean representing whether or not the link should be visible within the group.",
                                    "type": "boolean"
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

=== TrevorDBrown/LinkFree/src/templates/linkfree.json
{
    "displayName": "Your Name Here!",
    "tagline": "Some unique tagline for yourself!",
    "profilePicture": "./private/images/Profile.png",
    "theme": "DarkMode",
    "linkTrayOnTop": true,
    "links": [
        {
            "linkName": "A web link!",
            "linkType": "web",
            "inLinkTray": false,
            "linkPosition": 1,
            "linkHref": "https://github.com/TrevorDBrown/LinkFreePlus",
            "newWindow": true,
            "hide": false
        },
        {
            "linkName": "A link in the Link Tray!",
            "linkType": "web",
            "inLinkTray": true,
            "linkPosition": 1,
            "linkHref": "https://example.com/",
            "newWindow": true,
            "hide": false
        },
        {
            "linkName": "A hidden link...",
            "linkType": "web",
            "inLinkTray": false,
            "linkPosition": 2,
            "linkHref": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
            "newWindow": true,
            "hide": true
        },
        {
            "linkName": "A link that is in the Link Tray that has a special icon!",
            "linkType": "home",
            "inLinkTray": true,
            "linkPosition": 2,
            "linkHref": "",
            "newWindow": true,
            "hide": false
        }
    ]
}

=== TrevorDBrown/LinkFree/src/linkfree.json
{
    "displayName": "Trevor D. Brown",
    "theme": "DarkMode",
    "linkTrayOnTop": true,
    "links": [
        {
            "linkName": "Testing Link",
            "linkType": "web",
            "inLinkTray": false,
            "linkPosition": 1,
            "linkHref": "https://trevordylanbrown.com",
            "newWindow": true,
            "hide": false
        },
        {
            "linkName": "Facebook",
            "linkType": "facebook",
            "inLinkTray": true,
            "linkPosition": 1,
            "linkHref": "https://facebook.com/trevordylanbrown",
            "newWindow": true,
            "hide": false
        },
        {
            "linkName": "Twitter",
            "linkType": "twitter",
            "inLinkTray": true,
            "linkPosition": 2,
            "linkHref": "https://twitter.com/Trevor_D_Brown",
            "newWindow": false,
            "hide": false
        }
    ]
}

=== TrevorDBrown/LinkFree/src/templates/linkfree.json/linkfree.json
{
    "displayName": "Your Name Here!",
    "tagline": "Some unique tagline for yourself!",
    "profilePicture": "./private/images/Profile.png",
    "theme": "DarkMode",
    "linkTrayOnTop": true,
    "linkGroupsAboveUnsorted": false,
    "linkGroups": [
        {
            "linkGroupName": "A Link Group!",
            "showLinkGroupName": true,
            "useLinkIcons": false,
            "linkGroupPosition": 1,
            "linkGroupEnabled": true
        }
    ],
    "links": [
        {
            "linkName": "A web link!",
            "linkType": "web",
            "linkHref": "https://github.com/TrevorDBrown/LinkFreePlus",
            "newWindow": true,
            "enabled": true,
            "linkGroups": [
                {
                    "linkGroupName": "A Link Group!",
                    "linkPosition": 1,
                    "show": true
                }
            ]
        },
        {
            "linkName": "A link in the Link Tray!",
            "linkType": "web",
            "linkHref": "https://example.com/",
            "newWindow": true,
            "enabled": true,
            "linkGroups": [
                {
                    "linkGroupName": "Tray",
                    "linkPosition": 1,
                    "show": true
                }
            ]
        },
        {
            "linkName": "An enabled, but hidden link...",
            "linkType": "web",
            "linkHref": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
            "newWindow": true,
            "enabled": true,
            "linkGroups": [
                {
                    "linkGroupName": "Unsorted",
                    "linkPosition": 2,
                    "show": false
                }
            ]
        },
        {
            "linkName": "A disabled link...",
            "linkType": "web",
            "linkHref": "https://www.youtube.com/watch?v=dQw4w9WgXcQ",
            "newWindow": true,
            "enabled": false,
            "linkGroups": []
        },
        {
            "linkName": "A link that is in the Link Tray that has a special icon!",
            "linkType": "home",
            "linkHref": "",
            "newWindow": true,
            "enabled": true,
            "linkGroups": [
                {
                    "linkGroupName": "Tray",
                    "linkPosition": 2,
                    "show": true
                }
            ]
        }
    ]
}
